name: mono app publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} 
      - run: aws s3 sync ./build s3://$BUCKET_NAME/latest
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      - run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID
        env:
          DISTRIBUTION_ID: ${{ secrets.AWS_CF_DISTRIBUTION_ID }}          
